build:
  image: brettbj/continuous_analysis_brainarray_v20
  commands:
    - git status
    - tar -xvf /data/GSE47664_RAW.tar 
    - Rscript r_script.r

    - cd /drone/src/github.com/greenelab/continuous_analysis_brainarray
    - mkdir -p results
    - mv output.csv results/output.csv
    - mv truncated_output.csv results/truncated_output.csv

    - git config user.email "brettbj@gmail.com"
    - git config user.name "Brett Beaulieu-Jones"
    - git config --global push.default simple
    - git remote set-url origin https://github.com/greenelab/continuous_analysis_brainarray.git

    - git checkout master
    - git add results
    - git commit -a -m "Drone Build [skip ci] [ci skip]"
    - git remote set-url origin https://brettbj:$$git_publish_key@github.com/greenelab/continuous_analysis_brainarray.git
    - git fetch
    - git branch --set-upstream-to=origin/master master
    - git pull -s recursive -X theirs
    - git push 

branches:
  - staging
